### PR TITLE
Support Python range from 3.7 to 3.11

### PR DESCRIPTION
**Pull request by EliahKagan**
Thank you for making this plugin--I've found it very useful!

Currently, `pylint-actions` only supports Python 3.9 and higher. But the code itself is compatible with all versions of Python that `pylint` currently supports. This pull request widens the range of versions that `pylint-actions` can be installed on, to match the range `pylint` permits. Changing `"^3.9"` to `">=3.7.2,<4.0"` and rerunning `poetry lock` was sufficient to achieve this.

I noticed that this would trigger the `release.yml` workflow if merged to main, because it's a change to `pyproject.toml`, so I also went ahead and bumped the project version number, to permit that to succeed. **I can easily drop that second commit from the PR** if you prefer not to have it. I'd also be pleased to make any other requested changes.

I manually tested this against the `examples/` code with Python 3.7, 3.8, 3.9, 3.10, 3.11, and PyPy behaving as 3.8, on Ubuntu 20.04 LTS and Windows 10. The plugin always installed and produced good output.

### Rationale

Python 3.8 will remain [supported by the Python project](https://devguide.python.org/versions/#supported-versions) (and thus probably also `pylint`) until October 2024. Python 3.7 will only be supported for the next two months, but it's often still used on CI, so I've included it too.

Projects that target Python 3.7 or 3.8 can sometimes use 3.9+ on CI for `pylint`, but I think supporting all versions `pylint` supports is beneficial, because:

1. Linting jobs are often included in workflows with other jobs that need a specific version.

2. Running `pylint` gives a warning if a plugin that isn't installed is configured to be loaded, even if the output format it provides is not requested. This impacts experience *outside* CI, where one may still want to run `pylint` in a 3.7 or 3.8 environment and get clean output. If the plugin can be installed for those versions, the needed configuration is thus simplified.

The second situation is what I encountered, but the first situation is probably more important.

### CODE REVIEW

**Comment by skhomuti** [comment]
Thank you for your contribution! It's really make sense to add a wide python versions, let me looking at it within a couple days

P.S. Sorry for the late reply, I definitely should set up some notifications %)

**Comment by skhomuti** [comment]
I'll change some things right here if you don't mind

**Comment by EliahKagan** [comment]
@skhomuti Thanks!

(Please do go ahead and make any changes you like, of course. The "Allow edits..." box is checked, so GitHub should allow you to push to my branch.)

**Comment by skhomuti** [comment]
@EliahKagan thanks!

**Pull request merged**
